spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: routeportal
          uri: lb://routeportal
          predicates:
            - Path=/**
        - id: loginservice
          uri: lb://loginservice
          predicates:
            - Path=/**